apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: rugacoder/javaapp
        imagePullPolicy: Never
        ports:
        - containerPort: 8090


---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp
  ports:
  - port: 8090
    targetPort: 8090

